/**
 * Model Constants - Định nghĩa các hằng số cho models
 */

// User Roles
const USER_ROLES = {
  STUDENT: 'STUDENT',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN'
};

// User Status
const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

// Student Status
const STUDENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  GRADUATED: 'GRADUATED',
  SUSPENDED: 'SUSPENDED'
};

// Staff Status
const STAFF_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE'
};

// Admin Permissions
const ADMIN_PERMISSIONS = {
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
  CERTIFICATE_MANAGEMENT: 'CERTIFICATE_MANAGEMENT',
  NOTIFICATION_MANAGEMENT: 'NOTIFICATION_MANAGEMENT',
  REPORT_ACCESS: 'REPORT_ACCESS',
  FULL_ACCESS: 'FULL_ACCESS'
};

// Notification Types
const NOTIFICATION_TYPES = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  ANNOUNCEMENT: 'ANNOUNCEMENT'
};

// Notification Priority
const NOTIFICATION_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

// Certificate Template Variable Types
const TEMPLATE_VARIABLE_TYPES = {
  TEXT: 'TEXT',
  DATE: 'DATE',
  NUMBER: 'NUMBER'
};

// Validation Rules
const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 6,
  NAME_MAX_LENGTH: 50,
  EMAIL_REGEX: /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/,
  PHONE_REGEX: /^[0-9]{10,11}$/,
  STUDENT_ID_REGEX: /^[0-9A-Z]{8,12}$/,
  STAFF_ID_REGEX: /^[0-9A-Z]{6,10}$/,
  ADMIN_ID_REGEX: /^ADM[0-9]{4,6}$/
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  STUDENT_STATUS,
  STAFF_STATUS,
  ADMIN_PERMISSIONS,
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITY,
  TEMPLATE_VARIABLE_TYPES,
  VALIDATION_RULES
};
